### ISSUE TITLE
Support for Samsung Galaxy M51

### ISSUE THREAD

**Issue by debarkak** [ShaDisNX255/NcX_Stock#5]
hi, i always wanted one ui 5 on my samsung galaxy m51, however this NcX S21FE rom does not work on m51 (using A71 4G rom) as its stated that hw libs is only for a71 and not for m51, however the SoC of a71 and m51 (Snapdragon 730G) is the same, so it wont be hard to port this rom to M51 as well, i did try copying a modified version of the vendor from LmaoCatOS to the NcX rom, however that results in a permission issue, and unable to install... if you can port NcX rom to tge M51 i woulf be happy, and finally have One UI 5 with a13 (android13) on my M51, or maybe i would do it, who knows? teamwork is a thing.

**Comment by debarkak** [comment]
one thing to mention is yes ik the m51 didnt get the one ui 5 with a13 upgrade, however with project treble i was able to get a working android 13 (and 14) on my m51, and one ui 5 (from a71) using nippongsi, however lock screen does not work so, yeah....

**Comment by ShaDisNX255** [comment]
I do not have plans on releasing for M51, sorry.
